### ISSUE TITLE
Upload failed: 403 Forbidden

### ISSUE THREAD

**Issue by Pahonix** [madcowfred/wowthing-sync#2]
I've been getting "Upload failed: 403 Forbidden" in WoWthing Sync 0.2.0 for a while now, not sure how long ago it started. I just noticed it when I went to the site and saw things weren't getting updated. I manually uploaded the .lua file and that works fine. I've confirmed my username/password are correct.

**Comment by Pahonix** [comment]
Just as an update, I downloaded the latest version (0.3.0) and continue to have the same issue as above.

**Comment by madcowfred** [comment]
I've had a few people report this but haven't really been able to track down why. Your username is case-sensitive via sync, does it have/not have capital letters where it should? Uhh... does your password have any really weird characters?

**Comment by Pahonix** [comment]
Thanks very much for your response. I certainly feel dumb, but it was the case-sensitive thing. I capitalized my username and it worked. It was approaching a year on this ticket and I'm kicking myself that I didn't think of that. :)

**Comment by madcowfred** [comment]
I could probably remember to check the issues a bit more often too :(
